# -*- coding: utf-8 -*-
"""task2_data_processing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UhHaqX7tOoG78wlu5wJwAIJY2Va9LEKe
"""

# task2_data_processing.py

import pandas as pd
import os

# file path (make sure this file exists from task 1)
file_path = "data/trends_20260407.json"   # change date if needed

# check file exists
if not os.path.exists(file_path):
    print("file not found:", file_path)
else:
    # load json
    df = pd.read_json(file_path)

    print("Loaded", len(df), "stories from", file_path)

    # -------------------------------
    # remove duplicates
    df = df.drop_duplicates(subset="post_id")
    print("After removing duplicates:", len(df))

    # -------------------------------
    # remove missing values
    df = df.dropna(subset=["post_id", "title", "score"])
    print("After removing nulls:", len(df))

    # -------------------------------
    # fix data types
    df["score"] = df["score"].astype(int)
    df["num_comments"] = df["num_comments"].astype(int)

    # -------------------------------
    # remove low score
    df = df[df["score"] >= 5]
    print("After removing low scores:", len(df))

    # -------------------------------
    # remove extra spaces in title
    df["title"] = df["title"].str.strip()

    # -------------------------------
    # save csv
    output_file = "data/trends_clean.csv"
    df.to_csv(output_file, index=False)

    print("Saved", len(df), "rows to", output_file)

    # -------------------------------
    # summary per category
    print("\nStories per category:")
    print(df["category"].value_counts())