# -*- coding: utf-8 -*-
"""task1_data_collection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qITvShtKmwIYVEqUGUXhbHTb3Xwc0O1
"""

import requests
import json
import os
import time
from datetime import datetime

# api urls
top_url = "https://hacker-news.firebaseio.com/v0/topstories.json"
item_url = "https://hacker-news.firebaseio.com/v0/item/{}.json"

headers = {"User-Agent": "TrendPulse/1.0"}

# keywords
tech_list = ["ai", "tech", "software", "code", "data"]
news_list = ["war", "government", "election", "country"]
sports_list = ["game", "team", "player", "league"]
science_list = ["research", "space", "physics", "biology"]
ent_list = ["movie", "music", "film", "show"]

# category counts
cat_count = {
    "technology": 0,
    "worldnews": 0,
    "sports": 0,
    "science": 0,
    "entertainment": 0
}

data_store = []

# get story ids
try:
    res = requests.get(top_url, headers=headers)
    story_ids = res.json()
except:
    print("problem getting ids")
    story_ids = []

story_ids = story_ids[:500]

for sid in story_ids:

    print("working on story id:", sid)

    # stop if all categories done
    if all(v >= 25 for v in cat_count.values()):
        break

    try:
        r = requests.get(item_url.format(sid), headers=headers)
        story = r.json()
    except:
        print("error for", sid)
        continue

    if not story or "title" not in story:
        continue

    title = story["title"].lower()
    cat = None

    # check categories one by one
    for w in tech_list:
        if w in title:
            cat = "technology"
            break

    if cat is None:
        for w in news_list:
            if w in title:
                cat = "worldnews"
                break

    if cat is None:
        for w in sports_list:
            if w in title:
                cat = "sports"
                break

    if cat is None:
        for w in science_list:
            if w in title:
                cat = "science"
                break

    if cat is None:
        for w in ent_list:
            if w in title:
                cat = "entertainment"
                break

    if cat is None:
        continue

    if cat_count[cat] >= 25:
        continue

    # save data
    one_item = {
        "post_id": story.get("id"),
        "title": story.get("title"),
        "category": cat,
        "score": story.get("score", 0),
        "num_comments": story.get("descendants", 0),
        "author": story.get("by"),
        "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

    data_store.append(one_item)
    cat_count[cat] += 1

    # delay after category full
    if cat_count[cat] == 25:
        print("finished", cat)
        time.sleep(2)

# create folder
if not os.path.exists("data"):
    os.makedirs("data")

# filename
file_name = "data/trends_" + datetime.now().strftime("%Y%m%d") + ".json"

# save file
with open(file_name, "w", encoding="utf-8") as f:
    json.dump(data_store, f, indent=4)

print("Collected", len(data_store), "stories")
print("Saved to", file_name)