# -*- coding: utf-8 -*-
"""task3_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UhHaqX7tOoG78wlu5wJwAIJY2Va9LEKe
"""

# task3_analysis.py

import pandas as pd
import numpy as np
import os

file_path = "data/trends_clean.csv"

# check file
if not os.path.exists(file_path):
    print("file not found:", file_path)

else:
    # load csv
    df = pd.read_csv(file_path)

    print("Loaded data:", df.shape)

    # ---------------------------
    # first 5 rows
    print("\nFirst 5 rows:")
    print(df.head())

    # ---------------------------
    # averages
    avg_score = df["score"].mean()
    avg_comments = df["num_comments"].mean()

    print("\nAverage score   :", int(avg_score))
    print("Average comments:", int(avg_comments))

    # ---------------------------
    # numpy stats
    scores = df["score"].values

    print("\n--- NumPy Stats ---")
    print("Mean score   :", int(np.mean(scores)))
    print("Median score :", int(np.median(scores)))
    print("Std deviation:", int(np.std(scores)))
    print("Max score    :", int(np.max(scores)))
    print("Min score    :", int(np.min(scores)))

    # ---------------------------
    # most stories category
    cat_counts = df["category"].value_counts()
    top_cat = cat_counts.idxmax()
    print("\nMost stories in:", top_cat, "(", cat_counts.max(), "stories )")

    # ---------------------------
    # most commented story
    max_comments = df["num_comments"].idxmax()
    top_story = df.loc[max_comments]

    print("\nMost commented story:")
    print(top_story["title"], "-", int(top_story["num_comments"]), "comments")

    # ---------------------------
    # add new columns

    # engagement
    df["engagement"] = df["num_comments"] / (df["score"] + 1)

    # is_popular
    df["is_popular"] = df["score"] > avg_score

    # ---------------------------
    # save new file
    out_file = "data/trends_analysed.csv"
    df.to_csv(out_file, index=False)

    print("\nSaved to", out_file)