# -*- coding: utf-8 -*-
"""task4_visualization.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UhHaqX7tOoG78wlu5wJwAIJY2Va9LEKe
"""

# task4_visualization.py

import pandas as pd
import matplotlib.pyplot as plt
import os

# file path
file_path = "data/trends_analysed.csv"

# create outputs folder
if not os.path.exists("outputs"):
    os.makedirs("outputs")

# load data
df = pd.read_csv(file_path)

# -----------------------------
# CHART 1: Top 10 stories by score

# sort and take top 10
top10 = df.sort_values(by="score", ascending=False).head(10)

# shorten titles
titles = []
for t in top10["title"]:
    if len(t) > 50:
        titles.append(t[:50] + "...")
    else:
        titles.append(t)

plt.figure()
plt.barh(titles, top10["score"])
plt.xlabel("Score")
plt.ylabel("Title")
plt.title("Top 10 Stories by Score")

plt.tight_layout()
plt.savefig("outputs/chart1_top_stories.png")
plt.show()


# -----------------------------
# CHART 2: Stories per category

cat_counts = df["category"].value_counts()

plt.figure()
plt.bar(cat_counts.index, cat_counts.values)
plt.xlabel("Category")
plt.ylabel("Number of Stories")
plt.title("Stories per Category")

plt.tight_layout()
plt.savefig("outputs/chart2_categories.png")
plt.show()


# -----------------------------
# CHART 3: Scatter plot

# split popular and not popular
popular = df[df["is_popular"] == True]
not_popular = df[df["is_popular"] == False]

plt.figure()
plt.scatter(popular["score"], popular["num_comments"], label="Popular")
plt.scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")

plt.xlabel("Score")
plt.ylabel("Number of Comments")
plt.title("Score vs Comments")
plt.legend()

plt.tight_layout()
plt.savefig("outputs/chart3_scatter.png")
plt.show()


# -----------------------------
# BONUS: Dashboard

fig, axs = plt.subplots(1, 3, figsize=(15, 5))

# chart 1 in dashboard
axs[0].barh(titles, top10["score"])
axs[0].set_title("Top Stories")

# chart 2 in dashboard
axs[1].bar(cat_counts.index, cat_counts.values)
axs[1].set_title("Categories")

# chart 3 in dashboard
axs[2].scatter(popular["score"], popular["num_comments"], label="Popular")
axs[2].scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")
axs[2].set_title("Score vs Comments")

plt.suptitle("TrendPulse Dashboard")

plt.tight_layout()
plt.savefig("outputs/dashboard.png")
plt.show()

print("Charts saved in outputs folder")